[package]
name = "celesta-composition"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
ts-rs = { workspace = true, optional = true }

[features]
codegen = ["dep:ts-rs"]
