[package]
name = "celesta-gpu-renderer"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
bytemuck = "1.25.2"
image = { version = "0.25.8", default-features = false, features = ["jpeg", "png", "pnm", "webp"] }
celesta-composition = { path = "../composition" }
celesta-remote = { path = "../remote" }
celesta-media = { path = "../media" }
celesta-renderer = { path = "../renderer" }
naga = { version = "30.0.1", features = ["wgsl-in"] }
pollster = "0.4.0"
rayon = "1.12.0"
wgpu = { version = "30.0.1", features = ["naga-ir"] }

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.10.0"
core-video = { version = "0.5.2", features = ["metal"] }
foreign-types = "0.5.0"
metal = "0.33.0"
objc2 = "0.6.4"
objc2-metal = "0.3.2"
wgpu-hal = "30.0.1"

[dev-dependencies]
tempfile = "3.23.0"
