[package]
name = "celesta-renderer"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
cosmic-text = "0.18.2"
image = { version = "0.25.8", default-features = false, features = ["jpeg", "png", "pnm", "webp"] }
celesta-composition = { path = "../composition" }
celesta-remote = { path = "../remote" }
celesta-media = { path = "../media" }
png = "0.18.1"
psd = "0.3.5"

[target.'cfg(windows)'.dependencies]
dwrote = { version = "0.11.5", default-features = false }

[dev-dependencies]
celesta-evaluator = { path = "../evaluator" }
celesta-project = { path = "../project" }

[[example]]
name = "hello"
path = "examples/hello.rs"
