[package]
name = "celesta-editor-core"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
celesta-composition = { path = "../composition" }
celesta-evaluator = { path = "../evaluator" }
celesta-project = { path = "../project" }
serde_json.workspace = true

[dev-dependencies]
celesta-gpu-renderer = { path = "../gpu-renderer" }
