//! Installs and refreshes a project's `.celesta/` TypeScript support
//! directory from the template staged beside the runtime's `cli.js`
//! (`packages/react/scripts/stage-project-types.mjs`).
//!
//! Entries always run against the bundled `react` and `@celesta/react`, so
//! the project only needs matching declarations for editors and `tsc`.
//! Copying them from the running Celesta keeps them in step with the runtime
//! without a package registry or an install step.

use std::fs;
use std::io;
use std::path::{Path, PathBuf};

/// The directory created at a project root.
pub const PROJECT_TYPES_DIR: &str = ".celesta";

const TEMPLATE_DIR: &str = "project-types";
/// Content stamp written last, so an interrupted copy is redone later.
const STAMP: &str = "version.json";
const EXTENDS: &str = "./.celesta/tsconfig.json";

/// The support template staged next to `cli_script`.
pub fn project_types_template(cli_script: &Path) -> PathBuf {
    cli_script
        .parent()
        .unwrap_or_else(|| Path::new("."))
        .join(TEMPLATE_DIR)
}

/// How the project root's `tsconfig.json` relates to `.celesta/tsconfig.json`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ProjectTsconfig {
    /// No `tsconfig.json` existed; one extending the support config was written.
    Created,
    /// The existing `tsconfig.json` already extends the support config.
    Extends,
    /// The existing `tsconfig.json` was left alone and does not extend it yet.
    MissingExtends,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ProjectTypesSetup {
    pub root: PathBuf,
    pub tsconfig: ProjectTsconfig,
}

/// Installs `.celesta/` for `entry`'s project and writes a root
/// `tsconfig.json` when there is none. The root is the nearest ancestor of
/// the entry holding a `tsconfig.json` or `package.json`, else its directory.
pub fn set_up_project_types(template: &Path, entry: &Path) -> io::Result<ProjectTypesSetup> {
    let directory = entry_directory(entry)?;
    let root = directory
        .ancestors()
        .find(|dir| dir.join("tsconfig.json").is_file() || dir.join("package.json").is_file())
        .unwrap_or(&directory)
        .to_owned();
    install(template, &root)?;
    let path = root.join("tsconfig.json");
    let tsconfig = match fs::read_to_string(&path) {
        Ok(text) if text.contains(".celesta/tsconfig.json") => ProjectTsconfig::Extends,
        Ok(_) => ProjectTsconfig::MissingExtends,
        Err(error) if error.kind() == io::ErrorKind::NotFound => {
            fs::write(&path, format!("{{\n  \"extends\": \"{EXTENDS}\"\n}}\n"))?;
            ProjectTsconfig::Created
        }
        Err(error) => return Err(error),
    };
    Ok(ProjectTypesSetup { root, tsconfig })
}

/// Re-copies `.celesta/` when a project that already has one was set up by a
/// different Celesta build. Returns the refreshed root; projects that never
/// opted in, or a runtime without a template, are left untouched.
pub fn refresh_project_types(template: &Path, entry: &Path) -> io::Result<Option<PathBuf>> {
    let Ok(expected) = fs::read(template.join(STAMP)) else {
        return Ok(None);
    };
    let directory = entry_directory(entry)?;
    let Some(root) = directory
        .ancestors()
        .find(|dir| dir.join(PROJECT_TYPES_DIR).join(STAMP).is_file())
    else {
        return Ok(None);
    };
    if fs::read(root.join(PROJECT_TYPES_DIR).join(STAMP))? == expected {
        return Ok(None);
    }
    install(template, root)?;
    Ok(Some(root.to_owned()))
}

fn entry_directory(entry: &Path) -> io::Result<PathBuf> {
    let entry = std::path::absolute(entry)?;
    Ok(entry.parent().map_or_else(|| entry.clone(), Path::to_owned))
}

fn install(template: &Path, root: &Path) -> io::Result<()> {
    let stamp = fs::read(template.join(STAMP)).map_err(|error| {
        io::Error::new(
            error.kind(),
            format!(
                "TypeScript support files are missing from the Celesta runtime ({}): {error}",
                template.display()
            ),
        )
    })?;
    let target = root.join(PROJECT_TYPES_DIR);
    fs::create_dir_all(&target)?;
    match fs::remove_file(target.join(STAMP)) {
        Err(error) if error.kind() != io::ErrorKind::NotFound => return Err(error),
        _ => {}
    }
    let modules = target.join("node_modules");
    if modules.exists() {
        fs::remove_dir_all(&modules)?;
    }
    copy_dir(&template.join("node_modules"), &modules)?;
    fs::copy(template.join("tsconfig.json"), target.join("tsconfig.json"))?;
    fs::write(
        target.join(".gitignore"),
        "# Generated by Celesta and refreshed when Celesta updates.\n*\n",
    )?;
    fs::write(target.join(STAMP), stamp)
}

fn copy_dir(from: &Path, to: &Path) -> io::Result<()> {
    fs::create_dir_all(to)?;
    for entry in fs::read_dir(from)? {
        let entry = entry?;
        let destination = to.join(entry.file_name());
        if entry.file_type()?.is_dir() {
            copy_dir(&entry.path(), &destination)?;
        } else {
            fs::copy(entry.path(), destination)?;
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    struct Scratch(PathBuf);

    impl Scratch {
        fn new(name: &str) -> Self {
            let root = std::env::temp_dir().join(format!(
                "celesta-project-types-{name}-{}",
                std::process::id()
            ));
            let _ = fs::remove_dir_all(&root);
            fs::create_dir_all(&root).unwrap();
            Self(root)
        }
    }

    impl Drop for Scratch {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }

    fn write(path: &Path, contents: &str) {
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, contents).unwrap();
    }

    fn template(root: &Path, stamp: &str) -> PathBuf {
        let template = root.join("runtime/dist/project-types");
        write(&template.join(STAMP), stamp);
        write(&template.join("tsconfig.json"), "{}");
        write(
            &template.join("node_modules/@celesta/react/dist/index.d.ts"),
            stamp,
        );
        template
    }

    #[test]
    fn template_sits_beside_the_cli_script() {
        assert_eq!(
            project_types_template(Path::new("Resources/react/dist/cli.js")),
            Path::new("Resources/react/dist/project-types")
        );
    }

    #[test]
    fn set_up_installs_support_files_and_creates_a_tsconfig() {
        let scratch = Scratch::new("create");
        let template = template(&scratch.0, "v1");
        let project = scratch.0.join("video");
        write(&project.join("main.tsx"), "");

        let setup = set_up_project_types(&template, &project.join("main.tsx")).unwrap();

        assert_eq!(
            setup,
            ProjectTypesSetup {
                root: project.clone(),
                tsconfig: ProjectTsconfig::Created,
            }
        );
        let support = project.join(PROJECT_TYPES_DIR);
        assert_eq!(fs::read_to_string(support.join(STAMP)).unwrap(), "v1");
        assert!(support.join(".gitignore").is_file());
        assert!(support.join("tsconfig.json").is_file());
        assert!(
            support
                .join("node_modules/@celesta/react/dist/index.d.ts")
                .is_file()
        );
        assert!(
            fs::read_to_string(project.join("tsconfig.json"))
                .unwrap()
                .contains(EXTENDS)
        );
    }

    #[test]
    fn set_up_uses_the_nearest_package_root_and_keeps_its_tsconfig() {
        let scratch = Scratch::new("existing");
        let template = template(&scratch.0, "v1");
        let project = scratch.0.join("video");
        write(&project.join("package.json"), "{}");
        write(
            &project.join("tsconfig.json"),
            "{ \"compilerOptions\": {} }",
        );
        write(&project.join("src/main.tsx"), "");

        let setup = set_up_project_types(&template, &project.join("src/main.tsx")).unwrap();

        assert_eq!(setup.root, project);
        assert_eq!(setup.tsconfig, ProjectTsconfig::MissingExtends);
        assert_eq!(
            fs::read_to_string(project.join("tsconfig.json")).unwrap(),
            "{ \"compilerOptions\": {} }"
        );
    }

    #[test]
    fn refresh_updates_only_projects_set_up_by_another_build() {
        let scratch = Scratch::new("refresh");
        let old = template(&scratch.0.join("old"), "v1");
        let new = template(&scratch.0.join("new"), "v2");
        let project = scratch.0.join("video");
        let entry = project.join("src/main.tsx");
        write(&entry, "");

        assert_eq!(refresh_project_types(&new, &entry).unwrap(), None);
        assert!(!project.join(PROJECT_TYPES_DIR).exists());

        // Without a package root the entry's own directory is the root.
        let root = project.join("src");
        set_up_project_types(&old, &entry).unwrap();
        write(
            &root.join(PROJECT_TYPES_DIR).join("node_modules/stale.d.ts"),
            "",
        );
        assert_eq!(refresh_project_types(&old, &entry).unwrap(), None);
        assert_eq!(
            refresh_project_types(&new, &entry).unwrap(),
            Some(root.clone())
        );

        let support = root.join(PROJECT_TYPES_DIR);
        assert_eq!(fs::read_to_string(support.join(STAMP)).unwrap(), "v2");
        assert_eq!(
            fs::read_to_string(support.join("node_modules/@celesta/react/dist/index.d.ts"))
                .unwrap(),
            "v2"
        );
        assert!(!support.join("node_modules/stale.d.ts").exists());
    }

    #[test]
    fn refresh_without_a_template_leaves_the_project_alone() {
        let scratch = Scratch::new("no-template");
        let project = scratch.0.join("video");
        write(&project.join(PROJECT_TYPES_DIR).join(STAMP), "v1");
        let missing = scratch.0.join("missing");
        assert_eq!(
            refresh_project_types(&missing, &project.join("main.tsx")).unwrap(),
            None
        );
    }
}
